### PR TITLE
upload the original File artifacts to s3

### PR DESCRIPTION
**Pull request by johnduffell**
So this PR is to basically iterate through the teamcity artifacts directory and work out all the file names that need uploading.

This should leave the files on the disc under the control of team city, thus saving me from filling up the build machine embarassment.  However it might not work at all.

The TC docs mention something about locking the files before you start using them, but this may not apply at the end of the build.

@philwills I know you are so happy when other people contribute...

### CODE REVIEW

**Comment by philwills** [comment]
@johnduffell just tried this and, locally at least, it mostly works.  The only issue is it does also hoover up some internal Teamcity files.  You could either use the previous mechanism to filter them out, or alternatively, it looks like they're all under `.teamcity`, so you could exclude that and any children.

**Comment by johnduffell** [comment]
@philwills try again now

**Comment by philwills** [comment]
:+1: 

That seems to be working. Can you sort the merge conflicts, please?

**Comment by johnduffell** [comment]
@philwills okay I've done that now, hopefully it's right still ;)

**Pull request merged**
