### PR TITLE
Team city 9.1.1

### PR DESCRIPTION
**Pull request by rich-nguyen**
Builds the plugin against teamcity 9.1.1 libraries, and updates joda to fix an issue with java 8. https://github.com/aws/aws-sdk-java/issues/484

### CODE REVIEW

**Comment by philwills** [comment]
Can we give it a bigger version bump? Otherwise :+1:

**Comment by Kentzo** [comment]
@philwills Could you fix that and merge? Completely unusable with JDK 8 (recommended for TC 9.1.x)

**Comment by rich-nguyen** [comment]
@philwills just merged master, do you want me to publish at `1.4.1`?

**Comment by philwills** [comment]
@rich-nguyen I'd probably go for 1.5.0, but yes if you could do that and add a note to the README, that would be great. Thanks.

**Comment by mchv** [comment]
I will release `1.5.0` and update readme

**Pull request merged**
